-- Postgres (Neon) mirror of dataset.parquet, read by the Hermes profile `riskship`
-- (cron riesgo-envio-neon, script scripts/neon_fetch_shipments.sh).
-- Generated from the parquet schema: same 58 columns, same names (quoted,
-- case preserved), one row per shipment item exactly as in the dataset. Two
-- bookkeeping columns are added: id (the cron's watermark) and created_at.
-- Created and loaded by load_neon.py at the project root.
CREATE TABLE IF NOT EXISTS shipments (
  id          bigserial PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  "SHIPMENT_ID" text,
  "SHP_SHIPMENT_ID" text,
  "PAIS" text,
  "PICKING_TYPE" text,
  "FUE_AVION" boolean,
  "LG_FACILITY_NAME" text,
  "SHP_LG_FACILITY_ID" text,
  "LG_REGION" text,
  "DOM_DOMAIN_ID" text,
  "ITE_ITEM_ID" text,
  "ITE_ITEM_DESC" text,
  "ORD_CATEGORY_ID_L1" text,
  "ORD_CATEGORY_NAME_L1" text,
  "BRAND_NAME" text,
  "PESO_TOTAL_KG" bigint,
  "DIM_MAX_CM" bigint,
  "VALOR_TOTAL_USD" double precision,
  "CANTIDAD_ITEMS" bigint,
  "CANT_BULTOS" text,
  "ES_BULKY" boolean,
  "TIPO_BULKY" text,
  "RATIO_SVC_MES_ANTERIOR" double precision,
  "TOTALGMV" bigint,
  "BPP_CASHOUT_USD" double precision,
  "DATEPARAMETER" date,
  "CLASSIFICATION_LM" text,
  "SUBSTATUS_CLASIFICATION" text,
  "DATE_BPP" date,
  "CAUSA_BPP" text,
  "L1_CAUSA_BPP" text,
  "L2_CAUSA_BPP" text,
  "F_CLASIFICATION" text,
  "F_CLASIFICATION_STD" text,
  "date_status_0" timestamp,
  "status_0" text,
  "date_status_1" timestamp,
  "status_1" text,
  "date_status_2" timestamp,
  "status_2" text,
  "date_status_3" timestamp,
  "status_3" text,
  "date_status_4" timestamp,
  "status_4" text,
  "date_status_5" timestamp,
  "status_5" text,
  "date_status_6" timestamp,
  "status_6" text,
  "date_status_7" timestamp,
  "status_7" text,
  "date_status_8" timestamp,
  "status_8" text,
  "date_status_9" timestamp,
  "status_9" text,
  "date_status_10" timestamp,
  "status_10" text,
  "is_lost" bigint,
  "batch_num" bigint,
  "source_file" text
);
CREATE INDEX IF NOT EXISTS shipments_shipment_id_idx ON shipments ("SHIPMENT_ID");
CREATE INDEX IF NOT EXISTS shipments_created_at_idx ON shipments (created_at);
